services:
  - type: web
    name: canadian-house-price
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.index:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6